# Example workflow configurations for Odoo Tools

pipelines:
  # Full refactoring pipeline
  full_refactor:
    - type: detect
      from: HEAD~10
      to: HEAD
      output: detected_changes.csv
      threshold: 0.75

    - type: order
      path: .
      recursive: true
      strategy: semantic

    - type: rename
      csv: detected_changes.csv

  # Order only pipeline
  organize_code:
    - type: order
      path: ./sale
      recursive: true
      strategy: semantic

    - type: shell
      command: "black ./sale"

    - type: shell
      command: "isort ./sale"

  # Detection and review pipeline
  detect_changes:
    - type: detect
      from: main
      to: HEAD
      output: changes_for_review.csv
      threshold: 0.6

    - type: shell
      command: "echo 'Changes saved to changes_for_review.csv'"

  # Rename with validation
  apply_renames:
    - type: rename
      csv: approved_changes.csv

    - type: shell
      command: "python -m pytest tests/"

  # Module-specific refactor
  module_refactor:
    - type: detect
      from: HEAD~5
      to: HEAD
      output: module_changes.csv

    - type: order
      path: ./account
      recursive: true
      strategy: type

    - type: rename
      csv: module_changes.csv

    - type: shell
      command: "flake8 ./account"

  # Pre-commit workflow
  pre_commit:
    - type: order
      path: .
      recursive: false
      strategy: semantic

    - type: shell
      command: "black --check ."

    - type: shell
      command: "mypy ."