"""
Ordering rules and templates for Odoo source code organization.

This module contains all configuration for:
- Python code ordering (methods, fields, attributes)
- XML element and attribute ordering
- Section headers and formatting
"""

# ============================================================
# PYTHON MODEL ATTRIBUTE ORDERING
# ============================================================

MODEL_ATTRIBUTES: list[str] = [
    "_name",
    "_inherits",
    "_inherit",
    "_description",
    "_table",
    "_table_query",
    "_sequence",
    "_active_name",
    "_date_name",
    "_fold_name",
    "_parent_name",
    "_parent_store",
    "_parent_order",
    "_rec_name",
    "_rec_names_search",
    "_auto",
    "_abstract",
    "_check_company_auto",
    "_custom",
    "_depends",
    "_register",
    "_transient",
    "_transient_max_count",
    "_transient_max_hours",
    "_module",
    "_translate",
    "_allow_sudo_commands",
    "_log_access",
    "_order",
    "_check_company_domain",
]

# ============================================================
# FIELD ATTRIBUTE ORDERING
# ============================================================

# Field-type specific attribute ordering
# Each field type has its own optimal attribute order
FIELD_TYPE_ATTRIBUTES: dict[str, list[str]] = {
    # Relational fields
    "Many2one": [
        "related",
        "comodel_name",
        "string",
        "required",
        "default",
        "change_default",
        "compute",
        "compute_sudo",
        "store",
        "precompute",
        "recursive",
        "readonly",
        "inverse",
        "search",
        "bypass_search_access",
        "company_dependent",
        "check_company",
        "domain",
        "context",
        "ondelete",
        "auto_join",
        "copy",
        "groups",
        "index",
        "tracking",
        "help",
    ],
    "One2many": [
        "comodel_name",
        "inverse_name",
        "string",
        "compute",
        "store",
        "readonly",
        "domain",
        "context",
        "auto_join",
        "copy",
        "groups",
        "help",
    ],
    "Many2many": [
        "related",
        "depends",
        "comodel_name",
        "relation",
        "column1",
        "column2",
        "string",
        "required",
        "compute",
        "compute_sudo",
        "store",
        "precompute",
        "recursive",
        "readonly",
        "inverse",
        "search",
        "check_company",
        "domain",
        "context",
        "copy",
        "groups",
        "tracking",
        "help",
    ],
    # Basic fields
    "Char": [
        "related",
        "string",
        "required",
        "default",
        "size",
        "trim",
        "translate",
        "compute",
        "store",
        "precompute",
        "recursive",
        "readonly",
        "inverse",
        "search",
        "copy",
        "groups",
        "index",
        "tracking",
        "config_parameter",
        "help",
    ],
    "Text": [
        "related",
        "string",
        "required",
        "default",
        "translate",
        "compute",
        "store",
        "precompute",
        "readonly",
        "inverse",
        "search",
        "copy",
        "groups",
        "tracking",
        "help",
    ],
    "Html": [
        "related",
        "string",
        "required",
        "default",
        "translate",
        "sanitize",
        "sanitize_tags",
        "sanitize_attributes",
        "sanitize_style",
        "strip_style",
        "strip_classes",
        "compute",
        "store",
        "precompute",
        "readonly",
        "inverse",
        "search",
        "copy",
        "groups",
        "tracking",
        "help",
    ],
    # Numeric fields
    "Integer": [
        "related",
        "string",
        "required",
        "default",
        "compute",
        "compute_sudo",
        "store",
        "precompute",
        "readonly",
        "inverse",
        "search",
        "company_dependent",
        "copy",
        "groups",
        "index",
        "tracking",
        "help",
    ],
    "Float": [
        "related",
        "string",
        "digits",
        "required",
        "default",
        "compute",
        "compute_sudo",
        "store",
        "precompute",
        "readonly",
        "inverse",
        "search",
        "company_dependent",
        "aggregator",
        "group_operator",
        "copy",
        "groups",
        "index",
        "tracking",
        "help",
    ],
    "Monetary": [
        "related",
        "string",
        "currency_field",
        "required",
        "default",
        "compute",
        "store",
        "readonly",
        "inverse",
        "search",
        "copy",
        "groups",
        "tracking",
        "help",
    ],
    # Date/time fields
    "Date": [
        "related",
        "string",
        "required",
        "default",
        "compute",
        "store",
        "precompute",
        "readonly",
        "inverse",
        "search",
        "copy",
        "groups",
        "index",
        "tracking",
        "help",
    ],
    "Datetime": [
        "related",
        "string",
        "required",
        "default",
        "compute",
        "store",
        "precompute",
        "readonly",
        "inverse",
        "search",
        "copy",
        "groups",
        "index",
        "tracking",
        "help",
    ],
    # Selection field
    "Selection": [
        "related",
        "depends",
        "selection",
        "selection_add",
        "string",
        "required",
        "default",
        "compute",
        "store",
        "precompute",
        "readonly",
        "inverse",
        "search",
        "ondelete",
        "copy",
        "groups",
        "index",
        "tracking",
        "help",
    ],
    # Boolean field
    "Boolean": [
        "related",
        "string",
        "required",
        "default",
        "compute",
        "compute_sudo",
        "store",
        "precompute",
        "readonly",
        "inverse",
        "search",
        "company_dependent",
        "copy",
        "implied_group",
        "groups",
        "index",
        "tracking",
        "help",
    ],
    # Binary fields
    "Binary": [
        "related",
        "string",
        "required",
        "default",
        "readonly",
        "attachment",
        "compute",
        "store",
        "inverse",
        "search",
        "copy",
        "exportable",
        "groups",
        "help",
    ],
    "Image": [
        "related",
        "string",
        "required",
        "default",
        "attachment",
        "max_width",
        "max_height",
        "verify_resolution",
        "compute",
        "store",
        "readonly",
        "inverse",
        "search",
        "copy",
        "groups",
        "help",
    ],
    # Special fields
    "Reference": [
        "related",
        "selection",
        "string",
        "required",
        "default",
        "compute",
        "store",
        "readonly",
        "inverse",
        "search",
        "copy",
        "groups",
        "help",
    ],
    "Json": [
        "related",
        "string",
        "required",
        "default",
        "compute",
        "store",
        "readonly",
        "inverse",
        "search",
        "copy",
        "groups",
        "help",
    ],
    "Properties": [
        "related",
        "string",
        "definition",
        "required",
        "compute",
        "store",
        "readonly",
        "inverse",
        "search",
        "copy",
        "groups",
        "help",
    ],
}

# Generic fallback order for unknown field types
FIELD_ATTRIBUTE_GENERIC: list[str] = [
    "related",
    # Primary attributes
    "string",
    "required",
    "default",
    "translate",
    # Compute attributes
    "compute",
    "store",
    "readonly",
    "inverse",
    "search",
    "depends",
    # Default and copy
    "copy",
    # Constraints and UI
    "tracking",
    "groups",
    "index",
    "states",
    "company_dependent",
    # Help and documentation
    "deprecated",
    "oldname",
    "help",
]

# ============================================================
# PYTHON METHOD ORDERING
# ============================================================

SECTION_HEADERS: dict[str, str] = {
    "MODEL_ATTRIBUTES": "CLASS ATTRIBUTES",
    "FIELDS": "FIELDS",
    "COMPUTED_FIELDS": "COMPUTED FIELDS",
    "MODEL_INDEXES": "MODEL INDEXES",
    "CONSTRAINT": "CONSTRAINT METHODS",
    "SQL_CONSTRAINTS": "SQL CONSTRAINTS",
    "CRUD": "CRUD METHODS",
    "COMPUTE": "COMPUTE METHODS",
    "INVERSE": "INVERSE METHODS",
    "SEARCH": "SEARCH METHODS",
    "ONCHANGE": "ONCHANGE METHODS",
    "WORKFLOW": "WORKFLOW METHODS",
    "ACTIONS": "ACTION METHODS",
    "REPORT": "REPORT METHODS",
    "IMPORT_EXPORT": "IMPORT/EXPORT METHODS",
    "PORTAL": "PORTAL METHODS",
    "COMMUNICATION": "COMMUNICATION METHODS",
    "MAIL_THREAD": "MAIL THREAD METHODS",
    "WIZARD": "WIZARD METHODS",
    "INTEGRATION": "INTEGRATION METHODS",
    "CRON": "SCHEDULED METHODS",
    "ACCOUNTING": "ACCOUNTING METHODS",
    "MANUFACTURING": "MANUFACTURING METHODS",
    "PRODUCT_CATALOG": "PRODUCT CATALOG MIXIN METHODS",
    "OVERRIDE": "OVERRIDE METHODS",
    "API_MODEL": "API MODEL METHODS",
    "PREPARE": "PREPARE METHODS",
    "GETTER": "GETTER METHODS",
    "PUBLIC": "PUBLIC METHODS",
    "PRIVATE": "PRIVATE METHODS",
    "SECURITY": "SECURITY METHODS",
    "MISC": "MISCELLANEOUS",
}

# Standard Odoo method ordering
METHOD_ORDER: list[str] = [
    "CONSTRAINT",
    "CRUD",
    "COMPUTE",
    "INVERSE",
    "SEARCH",
    "ONCHANGE",
    "WORKFLOW",
    "WIZARD",
    "ACTIONS",
    "MAIL_THREAD",
    "COMMUNICATION",
    "PORTAL",
    "PREPARE",
    "GETTER",
    "REPORT",
    "IMPORT_EXPORT",
    "INTEGRATION",
    "CRON",
    "ACCOUNTING",
    "MANUFACTURING",
    "PRODUCT_CATALOG",
    "OVERRIDE",
    "SECURITY",
    "API_MODEL",
    "PUBLIC",
    "PRIVATE",
]


# ============================================================
# XML ATTRIBUTE ORDERING
# ============================================================

XML_ATTRIBUTE_ORDER: dict[str, list[str]] = {
    # Default order for any element
    # Default order for any element
    "_default": [
        "id",
        "name",
        "model",
        "string",
        "type",
        "class",
        "position",
        "attrs",
        "states",
        "invisible",
        "readonly",
        "required",
    ],
    # Specific orders for Odoo XML elements
    "record": ["id", "model", "forcecreate"],
    "field": [
        "name",
        "type",
        "string",
        "widget",
        "required",
        "readonly",
        "invisible",
        "attrs",
        "states",
        "help",
        "placeholder",
    ],
    "button": [
        "name",
        "string",
        "type",
        "class",
        "icon",
        "states",
        "attrs",
        "invisible",
        "confirm",
        "context",
    ],
    "tree": [
        "string",
        "default_order",
        "create",
        "edit",
        "delete",
        "duplicate",
        "import",
        "export_xlsx",
        "multi_edit",
        "sample",
    ],
    "form": ["string", "create", "edit", "delete", "duplicate"],
    "kanban": [
        "default_group_by",
        "class",
        "sample",
        "quick_create",
        "quick_create_view",
    ],
    "search": ["string"],
    "group": [
        "name",
        "string",
        "col",
        "colspan",
        "attrs",
        "invisible",
    ],
    "notebook": [
        "colspan",
        "attrs",
        "invisible",
    ],
    "page": [
        "name",
        "string",
        "attrs",
        "invisible",
    ],
    "xpath": ["expr", "position"],
    "attribute": ["name"],
    "div": [
        "class",
        "attrs",
        "invisible",
    ],
    "span": [
        "class",
        "attrs",
        "invisible",
    ],
    "t": [
        "t-if",
        "t-elif",
        "t-else",
        "t-foreach",
        "t-as",
        "t-esc",
        "t-raw",
        "t-field",
        "t-options",
        "t-set",
        "t-value",
        "t-call",
        "t-call-assets",
    ],
    "template": [
        "id",
        "name",
        "inherit_id",
        "priority",
    ],
    "menuitem": [
        "id",
        "name",
        "parent",
        "sequence",
        "action",
        "groups",
    ],
    "act_window": [
        "id",
        "name",
        "model",
        "view_mode",
        "domain",
        "context",
    ],
}


# ============================================================
# VIEW STRUCTURE TEMPLATES
# ============================================================

FORM_VIEW_STRUCTURE = {
    "sections": [
        "header",
        "sheet",
        "chatter",
    ],
    "sheet_order": [
        "title",
        "main_groups",
        "notebook",
        "footer_groups",
    ],
    "title_elements": [
        "h1",
        "h2",
        "div.o_title",
    ],
    "chatter_fields": [
        "message_follower_ids",
        "activity_ids",
        "message_ids",
    ],
}

TREE_VIEW_STRUCTURE = {
    "sections": [
        "control",
        "buttons",
        "fields",
        "widgets",
    ],
    "control_elements": [
        "control",
    ],
    "widget_types": [
        "widget",
        "progressbar",
        "badge",
    ],
}

SEARCH_VIEW_STRUCTURE = {
    "sections": [
        "fields",
        "filters",
        "separators",
        "groups",
    ],
    "separator_after_filters": True,
    "group_prefix": "group_by_",
}

KANBAN_VIEW_STRUCTURE = {
    "sections": [
        "progressbar",
        "fields",
        "control",
        "templates",
    ],
    "template_names": ["kanban-box"],
}
